"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.isNumber = exports.isNotEmptyString = exports.isEmptyString = exports.isString = exports.isFalse = exports.isTrue = exports.isNotEmptyArray = exports.isEmptyArray = exports.isAry = exports.isNotAllSet = exports.isNotSet = exports.isSet = void 0;
const isSet = (obj) => obj !== null && obj !== undefined;
exports.isSet = isSet;
const isNotSet = (obj) => obj === null || obj === undefined;
exports.isNotSet = isNotSet;
const isNotAllSet = (obj) => obj.some(exports.isNotSet);
exports.isNotAllSet = isNotAllSet;
const isAry = (ary) => Array.isArray(ary);
exports.isAry = isAry;
const isEmptyArray = (ary) => (0, exports.isAry)(ary) && ary.length === 0;
exports.isEmptyArray = isEmptyArray;
const isNotEmptyArray = (ary) => (0, exports.isAry)(ary) && ary.length !== 0;
exports.isNotEmptyArray = isNotEmptyArray;
const isTrue = (boolean) => boolean === true;
exports.isTrue = isTrue;
const isFalse = (boolean) => boolean === false;
exports.isFalse = isFalse;
const isString = (str) => typeof str === 'string';
exports.isString = isString;
const isEmptyString = (str) => (0, exports.isString)(str) && str.length === 0;
exports.isEmptyString = isEmptyString;
const isNotEmptyString = (str) => (0, exports.isString)(str) && str.length !== 0;
exports.isNotEmptyString = isNotEmptyString;
const isNumber = (any) => typeof any === 'number';
exports.isNumber = isNumber;
//# sourceMappingURL=formatChecker.js.map